from pathlib import Path
import unittest


class PublicWebsiteMessagingTests(unittest.TestCase):
    def test_srt1_core_homepage_centers_idea_to_completion_lifecycle(self):
        root = Path(__file__).resolve().parents[1]
        homepage = (root / "srt1_platform" / "pwa" / "srt1-core.html").read_text(encoding="utf-8")
        hero = (root / "srt1_platform" / "pwa" / "templates" / "home-hero.html").read_text(encoding="utf-8")
        pricing = (root / "srt1_platform" / "pwa" / "templates" / "home-pricing.html").read_text(encoding="utf-8")
        dashboard = (root / "srt1_platform" / "pwa" / "dashboard.html").read_text(encoding="utf-8")
        experience = (root / "srt1_platform" / "pwa" / "experience.html").read_text(encoding="utf-8")
        auth = (root / "srt1_platform" / "pwa" / "auth.html").read_text(encoding="utf-8")

        for content in (homepage, hero):
            self.assertIn("Bring the idea once.", content)
            self.assertIn("SRT-1 carries it to completion.", content)
            self.assertIn("living work environments", content)
            self.assertIn("approve completion without re-explaining the mission", content)
            self.assertNotIn("Your AI finally understands", content)

        self.assertIn("A seed grows into", homepage)
        self.assertIn("Plant Seed", homepage)
        self.assertIn("Create WorkCell", homepage)
        self.assertIn("Talk With The Work", homepage)
        self.assertIn("Verify And Complete", homepage)
        self.assertIn("Projects: choose what SRT-1 should understand and manage", homepage)
        self.assertIn("Active Work dashboard", pricing)
        self.assertIn("Welcome to SRT-1 Active Work", dashboard)
        self.assertIn("Plant ideas, guide WorkCells, verify progress, and approve completion", dashboard)
        self.assertIn("href=\"experience.html\"", homepage)
        self.assertIn("next=experience.html", homepage)
        self.assertIn("target = 'experience.html'", auth)
        self.assertIn("https://seedreflections.netlify.app/", homepage)

        self.assertNotIn("<!-- FRONT DOOR -->", experience)
        self.assertNotIn("Good afternoon, Darnell.", experience)
        self.assertNotIn("Tell me about your idea.", experience)
        self.assertIn('<section class="conversation" aria-label="SRT-1 Standard Experience">', experience)
        self.assertIn("SRT-1 Standard Experience", experience)
        self.assertIn("Bring the idea once.", experience)
        self.assertIn("keeps the assistant on task", experience)
        self.assertIn("carries the work to completion", experience)
        self.assertNotIn("Active mission", experience)
        self.assertNotIn("mission-strip", experience)
        self.assertIn("left: 50%", experience)
        self.assertIn("transform: translateX(-50%)", experience)
        self.assertIn("calc(100vw - 28px)", experience)
        self.assertIn("overflow-x: hidden", experience)
        self.assertIn("Tell SRT-1 what you want to create, connect, understand, plan, execute, observe, review, inspect, collaborate, learn, manage, or search", experience)
        self.assertIn("OWNER_INTENTS", experience)
        self.assertIn("classifyOwnerIntent", experience)
        for intent in ("create", "connect", "understand", "plan", "execute", "observe", "review", "inspect", "collaborate", "learn", "manage", "search"):
            self.assertIn(f"{intent}:", experience)
        self.assertIn("context-card", experience)
        self.assertIn("addContextCard", experience)
        self.assertIn("renderSessionBrief", experience)
        self.assertIn("Reviews, verification, project intelligence, and assistant activity will appear here only when they matter", experience)
        self.assertIn("project-trigger", experience)
        self.assertIn("project-menu", experience)
        self.assertIn("Choose folder", experience)
        self.assertIn("Paste local path", experience)
        self.assertIn("Attach file", experience)
        self.assertIn("Connect or attach", experience)
        self.assertIn("What do you want SRT-1 to do?", experience)
        self.assertIn("handleFileAttachment", experience)
        self.assertIn("handleIntent", experience)
        self.assertIn("createWorkFromIntent", experience)
        self.assertIn("showProjectBrief", experience)
        self.assertIn("showReviewContext", experience)
        self.assertIn("continueActiveWork", experience)
        self.assertIn("showConnectorStatus", experience)
        self.assertIn("searchConversationAndState", experience)
        self.assertIn("showCollaborationStatus", experience)
        self.assertIn("saveLearningIntent", experience)
        self.assertIn("/task", experience)
        self.assertIn("standard_experience_attachment", experience)
        self.assertIn('id="fileInput"', experience)
        self.assertIn("Use current workspace", experience)
        self.assertIn("Connect GitHub", experience)
        self.assertIn("Project registered", experience)
        self.assertIn("Project ready", experience)
        self.assertIn("Launch project runtime", experience)
        self.assertIn("Approve", experience)
        self.assertIn("Send back", experience)
        self.assertIn("Open project workspace", experience)
        self.assertIn("Open project Control Room", experience)
        self.assertIn("data-action-kind", experience)
        self.assertIn("workcellAction", experience)
        self.assertIn("Control Room", experience)
        self.assertIn("dashboard.html", experience)
        self.assertIn("loadWorkspace", experience)
        self.assertIn("/dashboard-summary", experience)
        self.assertIn("/api/v1/repositories/launch", experience)
        self.assertIn("/api/v1/repositories/register-path", experience)
        self.assertIn("/api/v1/repositories/browse-folder", experience)
        self.assertIn("/api/v1/repositories/register-current", experience)
        self.assertIn("/api/v1/workcells", experience)
        self.assertIn("/messages?limit=30", experience)
        self.assertIn("/chat", experience)
        self.assertIn("/action", experience)

        self.assertNotIn("Project Intelligence", experience)
        self.assertNotIn("Project Conversation", experience)
        self.assertNotIn('aria-label="Project status"', experience)
        self.assertNotIn("Permanent", experience)
        self.assertNotIn(">Current Work<", experience)
        self.assertNotIn("Previous Work", experience)
        self.assertNotIn("Mission Activity", experience)
        self.assertNotIn("Ask SRT-1 what you want to create, connect", experience)
        self.assertNotIn("While you were away", experience)
        self.assertNotIn("Today's recommendation", experience)
        self.assertNotIn("Project connected:", experience)
        self.assertNotIn("I read the backend state SRT-1 prepared for this project.", experience)
        self.assertNotIn("send-icon-button", experience)
        self.assertNotIn('id="projectView"', experience)
        self.assertNotIn('id="preparingView"', experience)
        self.assertNotIn("combinedWorkspace", experience)
        self.assertNotIn("parallelWorkspace", experience)
        self.assertNotIn("Project Controller", experience)
        self.assertNotIn("status-row", experience)
        self.assertNotIn("intelligence widgets", experience)
        self.assertNotIn("Repository Intelligence", experience)
        self.assertNotIn("Constellation</strong>", experience)
        self.assertNotIn("RecallPacket", experience)
        self.assertNotIn('<div class="speaker">S1</div>', experience)
        self.assertNotIn("function routeIntent", experience)


if __name__ == "__main__":
    unittest.main()
