from pathlib import Path
import unittest


class PublicWebsiteMessagingTests(unittest.TestCase):
    def test_srt1_core_homepage_centers_idea_to_completion_lifecycle(self):
        root = Path(__file__).resolve().parents[1]
        homepage = (root / "srt1_platform" / "pwa" / "srt1-core.html").read_text(encoding="utf-8")
        hero = (root / "srt1_platform" / "pwa" / "templates" / "home-hero.html").read_text(encoding="utf-8")
        pricing = (root / "srt1_platform" / "pwa" / "templates" / "home-pricing.html").read_text(encoding="utf-8")
        dashboard = (root / "srt1_platform" / "pwa" / "dashboard.html").read_text(encoding="utf-8")
        experience = (root / "srt1_platform" / "pwa" / "experience.html").read_text(encoding="utf-8")
        auth = (root / "srt1_platform" / "pwa" / "auth.html").read_text(encoding="utf-8")

        for content in (homepage, hero):
            self.assertIn("Bring the idea once.", content)
            self.assertIn("SRT-1 carries it to completion.", content)
            self.assertIn("living work environments", content)
            self.assertIn("approve completion without re-explaining the mission", content)
            self.assertNotIn("Your AI finally understands", content)

        self.assertIn("A seed grows into", homepage)
        self.assertIn("Plant Seed", homepage)
        self.assertIn("Create WorkCell", homepage)
        self.assertIn("Talk With The Work", homepage)
        self.assertIn("Verify And Complete", homepage)
        self.assertIn("Projects: choose what SRT-1 should understand and manage", homepage)
        self.assertIn("Active Work dashboard", pricing)
        self.assertIn("Welcome to SRT-1 Active Work", dashboard)
        self.assertIn("Repository intelligence, runtime evidence, verification, and diagnostics", dashboard)
        self.assertIn("Open Standard Experience", dashboard)
        self.assertIn("Continue in Standard Experience", dashboard)
        self.assertIn("href=\"experience.html\"", homepage)
        self.assertIn("next=experience.html", homepage)
        self.assertIn("target = 'experience.html'", auth)
        self.assertIn("https://seedreflections.netlify.app/", homepage)

        self.assertNotIn("<!-- FRONT DOOR -->", experience)
        self.assertNotIn("Good afternoon, Darnell.", experience)
        self.assertNotIn("Tell me about your idea.", experience)
        self.assertIn('<section class="conversation" aria-label="SRT-1 Standard Experience">', experience)
        self.assertIn("SRT-1 Standard Experience", experience)
        self.assertNotIn("Active mission", experience)
        self.assertNotIn("mission-strip", experience)
        self.assertIn("left: 50%", experience)
        self.assertIn("transform: translateX(-50%)", experience)
        self.assertIn("calc(100vw - 28px)", experience)
        self.assertIn("overflow-x: hidden", experience)
        self.assertIn("Tell SRT-1 what you want to create, connect, understand, plan, execute, observe, review, inspect, collaborate, learn, manage, or search", experience)
        self.assertIn("OWNER_INTENTS", experience)
        self.assertIn("classifyOwnerIntent", experience)
        self.assertIn("explicitlyRequestsScopedWork", experience)
        self.assertIn("shouldCreateBoundedWork", experience)
        self.assertIn("if (!shouldCreateBoundedWork(text, intent))", experience)
        for intent in ("create", "connect", "understand", "plan", "execute", "observe", "review", "inspect", "collaborate", "learn", "manage", "search"):
            self.assertIn(f"{intent}:", experience)
        self.assertIn("context-card", experience)
        self.assertIn("addContextCard", experience)
        self.assertIn("renderSessionBrief", experience)
        self.assertIn("renderStarterGateway", experience)
        self.assertIn("SRT-1 onboarding intake", experience)
        self.assertIn("Project intake", experience)
        self.assertIn("Choose the project SRT-1 should understand.", experience)
        self.assertIn("Onboarding is separate from the workstation", experience)
        self.assertIn("resetToStarterGateway", experience)
        self.assertIn("kind === 'start-new'", experience)
        self.assertIn("Start new project", experience)
        self.assertIn("const startFresh = pageParameters.get('start') === '1'", experience)
        self.assertIn("if (startFresh)", experience)
        self.assertIn(".conversation.starter-mode .composer { display: none; }", experience)
        self.assertIn(".conversation.starter-mode::-webkit-scrollbar { width: 6px; }", experience)
        self.assertIn("scrollbar-color: #344050 transparent", experience)
        self.assertIn(">Choose a project<", experience)
        self.assertIn("projectName.textContent = 'Choose a project'", experience)
        self.assertIn("Open the advanced technical Control Room", experience)
        self.assertIn("Continue ${remembered.name || 'last project'}", experience)
        self.assertIn("Choose registered", experience)
        self.assertIn("Reviews, verification, project intelligence, and assistant activity will appear here only when they matter", experience)
        self.assertIn("project-trigger", experience)
        self.assertIn("project-menu", experience)
        self.assertIn("Choose folder", experience)
        self.assertIn("Paste local path", experience)
        self.assertIn("Attach file", experience)
        self.assertIn("Connect or attach", experience)
        self.assertIn("What do you want SRT-1 to do?", experience)
        self.assertIn("handleFileAttachment", experience)
        self.assertIn("analyzeAttachedFile", experience)
        self.assertIn("File received and understood", experience)
        self.assertIn("Talk about this file", experience)
        self.assertIn("showAttachmentDiscussion", experience)
        self.assertIn("handleIntent", experience)
        self.assertIn("createWorkFromIntent", experience)
        self.assertIn("showProjectBrief", experience)
        self.assertIn("showReviewContext", experience)
        self.assertIn("continueActiveWork", experience)
        self.assertIn("showConnectorStatus", experience)
        self.assertIn("searchConversationAndState", experience)
        self.assertIn("showCollaborationStatus", experience)
        self.assertIn("saveLearningIntent", experience)
        self.assertIn("/task", experience)
        self.assertIn("standard_experience_attachment", experience)
        self.assertIn('id="fileInput"', experience)
        self.assertIn("Use current workspace", experience)
        self.assertIn("Connect GitHub", experience)
        self.assertIn("Repository registered", experience)
        self.assertIn("Repository understood", experience)
        self.assertIn("Launch project runtime", experience)
        self.assertIn("Approve", experience)
        self.assertIn("Send back", experience)
        self.assertIn("Open project workspace", experience)
        self.assertIn("Open project Control Room", experience)
        self.assertIn("data-action-kind", experience)
        self.assertIn("workcellAction", experience)
        self.assertIn("Control Room", experience)
        self.assertIn("dashboard.html", experience)
        self.assertIn("loadWorkspace", experience)
        self.assertIn("/dashboard-summary", experience)
        self.assertIn("/api/v1/repositories/launch", experience)
        self.assertIn("waitForRepositoryUnderstanding", experience)
        self.assertIn("experience.html?ready=1", experience)
        self.assertIn("const resumeRuntime = pageParameters.get('resume') === '1'", experience)
        self.assertIn("const readyRuntime = pageParameters.get('ready') === '1'", experience)
        self.assertIn("const shouldResumeWorkspace", experience)
        self.assertIn("if (readyRuntime) await loadCurrentRepositoryDiscussion()", experience)
        self.assertIn("kind === 'launch'", experience)
        self.assertIn("await launchProject(button.dataset.repoId)", experience)
        self.assertIn("if (repoId && repoId !== activeRepoId)", experience)
        self.assertIn("window.location.assign(runtimeUrl(port, 'experience.html?ready=1'))", experience)
        self.assertIn("result.runtime_port && ['ready', 'running'].includes(result.status)", experience)
        self.assertNotIn("const launchButton = event.target.closest", experience)
        self.assertIn("/synopsis", experience)
        self.assertIn("Repository Understanding has not returned", experience)
        self.assertIn("Would you like to talk about what this project is, or begin working on it?", experience)
        self.assertIn("showRepositoryDiscussion", experience)
        self.assertIn("loadCurrentRepositoryDiscussion", experience)
        self.assertIn("repository-discussion-live", experience)
        self.assertIn("API = origin", experience)
        self.assertIn("pendingRepositoryActivation", experience)
        self.assertIn("srt1_pending_repository_activation", experience)
        self.assertIn("Resuming Repository Understanding", experience)
        self.assertIn("previous project's WorkCell", experience)
        self.assertIn("Selected folder inspected", experience)
        self.assertIn("found no supported source files to map", experience)
        self.assertIn("asksAboutUpload", experience)
        self.assertIn("asksAboutSelectedProject", experience)
        self.assertNotIn("if (files > 0 && synopsisData.synopsis)", experience)
        self.assertNotIn("I found a Python backend, PWA frontend, tests, and WorkCell runtime.", experience)
        self.assertIn("/api/v1/repositories/register-path", experience)
        self.assertIn("/api/v1/repositories/browse-folder", experience)
        self.assertIn("/api/v1/repositories/register-current", experience)
        self.assertIn("/api/v1/workcells", experience)
        self.assertIn("/messages?limit=30", experience)
        self.assertIn("/chat", experience)
        self.assertIn("/action", experience)
        self.assertIn('id="workcellSelector"', experience)
        self.assertIn("workcellProviderSessions = new Map()", experience)
        self.assertIn("Project Assistant", experience)
        self.assertIn("projectAssistantOverlay", experience)
        self.assertIn("converseAboutProject", experience)
        self.assertIn("localProjectResponse", experience)
        self.assertIn("showLocalProjectResponse", experience)
        self.assertIn("SRT-1 project understanding", experience)
        self.assertIn("Connect Project Assistant", experience)
        self.assertIn("showLocalProjectResponse(message, understanding)", experience)
        self.assertNotIn("Project conversation needs an assistant", experience)
        self.assertIn("ensureRepositoryUnderstanding", experience)
        self.assertIn("Project Assistant: Not connected", experience)
        self.assertIn("await loadCurrentRepositoryDiscussion()", experience)
        self.assertIn("briefBtn').addEventListener('click', () => converseAboutProject('Explain this project.'))", experience)
        self.assertIn("const result = await postJson('/api/v1/project-conversation'", experience)
        self.assertIn("srt1_core'} answered from SRT-1 repository evidence", experience)
        self.assertIn("showLocalProjectResponse(message, understanding)", experience)
        self.assertIn("await converseAboutProject(text)", experience)
        self.assertIn("showWorkRequestConfirmation", experience)
        self.assertIn("Ready to create scoped work?", experience)
        self.assertIn("Requires your explicit WorkCell approval", experience)
        self.assertIn("Create a scoped WorkCell seed for:", experience)
        self.assertIn("else await showWorkRequestConfirmation(text)", experience)
        self.assertIn("Help me plan the first safe WorkCell for this project.", experience)
        self.assertNotIn("Create a scoped WorkCell seed for the first safe change in this project.", experience)
        self.assertIn("workcellReadinessFacts", experience)
        self.assertIn("auto_dispatch: false", experience)
        self.assertIn("The assistant has not been dispatched yet.", experience)
        self.assertIn("Open Package", experience)
        self.assertIn("Choose/Run Assistant", experience)
        self.assertIn("Message WorkCell", experience)
        self.assertIn("kind === 'workcell-console'", experience)
        self.assertIn("openWorkcellConsole(button.dataset.consoleTab || 'overview')", experience)
        self.assertLess(
            experience.index("if (['plan', 'tasks', 'estimate', 'prioritize', 'milestone']"),
            experience.index("if (['add', 'build', 'start', 'create', 'generate', 'brainstorm']"),
        )
        self.assertIn("/api/v1/project-conversation", experience)
        self.assertIn("projectConversationHistory", experience)
        self.assertIn("No Seed was created and no write scope was granted", experience)
        self.assertIn("getWorkcellProviderSession(execution.queue_seed_id)", experience)
        self.assertIn("Codex WorkCell handoff", experience)
        self.assertIn("providerRequiresSessionKey", experience)
        self.assertIn("assistantAdapterForSession", experience)
        self.assertIn("No API key required for Codex handoff", experience)
        self.assertIn("const defaultProvider = seedId === '__project__' ? 'openai' : 'codex'", experience)
        self.assertIn("enabled: defaultProvider === 'codex'", experience)
        self.assertIn("Codex handoff writes bounded WorkCell instructions", experience)
        self.assertIn("assistant_adapter:", experience)
        self.assertIn("assistant_credentials:", experience)
        self.assertIn("provider_keys: { [session.provider]: session.key }", experience)
        self.assertIn("anthropic: { endpoint: 'https://api.anthropic.com/v1/messages'", experience)
        self.assertIn("gemini: { endpoint: 'https://generativelanguage.googleapis.com", experience)
        self.assertIn("session.provider === 'anthropic' ? 'anthropic'", experience)
        self.assertIn("session.provider === 'gemini' ? 'gemini'", experience)
        self.assertIn("Respond automatically when I message this WorkCell", experience)
        self.assertIn("The key stays only in this browser tab's memory", experience)
        self.assertIn("srt1_pending_prompt", experience)
        self.assertIn("Review or revise it", experience)
        self.assertNotIn("localStorage.setItem('workcellProvider", experience)
        self.assertNotIn('localStorage.setItem("workcellProvider', experience)
        self.assertNotIn("localStorage.setItem('projectProvider", experience)

        self.assertNotIn("Project Intelligence", experience)
        self.assertNotIn("Project Conversation", experience)
        self.assertNotIn('aria-label="Project status"', experience)
        self.assertNotIn("Permanent", experience)
        self.assertNotIn(">Current Work<", experience)
        self.assertNotIn("Previous Work", experience)
        self.assertNotIn("Mission Activity", experience)
        self.assertNotIn("Ask SRT-1 what you want to create, connect", experience)
        self.assertNotIn("While you were away", experience)
        self.assertNotIn("Today's recommendation", experience)
        self.assertNotIn("Project connected:", experience)
        self.assertNotIn("I read the backend state SRT-1 prepared for this project.", experience)
        self.assertNotIn("send-icon-button", experience)
        self.assertNotIn('id="projectView"', experience)
        self.assertNotIn('id="preparingView"', experience)
        self.assertNotIn("combinedWorkspace", experience)
        self.assertNotIn("parallelWorkspace", experience)
        self.assertNotIn("Project Controller", experience)
        self.assertNotIn("status-row", experience)
        self.assertNotIn("intelligence widgets", experience)
        self.assertNotIn("Repository Intelligence", experience)
        self.assertNotIn("Constellation</strong>", experience)
        self.assertNotIn("RecallPacket", experience)
        self.assertNotIn('<div class="speaker">S1</div>', experience)
        self.assertNotIn("function routeIntent", experience)


if __name__ == "__main__":
    unittest.main()
