#!/usr/bin/env python3
"""
SRT-1 Seed Queue — Lifecycle Management
==========================================

Tracks every seed from planting to completion.

Lifecycle Stages (The Growth Metaphor):
    🌱 PLANTED      — Seed received, queued for processing
    🌿 GERMINATING  — Blueprint generated, dispatched to assistant
    🌳 GROWING      — Assistant is building, files being modified
    🌸 BLOOMED      — Seed completed successfully
    🍂 WILTED       — Seed failed or was abandoned
    ⏸️  PAUSED       — Seed temporarily paused by user

Each seed maintains:
    - The original intent (what the user asked for)
    - The generated blueprint (what was dispatched)
    - File changes detected (what was built)
    - Coherence score throughout lifecycle
    - Timestamps for every state transition
    - Success indicator (growth percentage 0-100%)

This is the queue that lets a user plant a seed from their phone,
walk away, and come back to see "🌸 BLOOMED — 3 files modified,
all tests passing, coherence 94%."

Author : William Darnell Jernigan IV (Architect)
License: Apache License 2.0
"""

import os
import json
import time
import hashlib
import logging
from datetime import datetime
from typing import Dict, List, Any, Optional
from enum import Enum

logger = logging.getLogger("srt1.seeds")


class SeedStage(Enum):
    """The lifecycle stages of a seed."""
    PLANTED     = "planted"       # 🌱 Received, queued
    GERMINATING = "germinating"   # 🌿 Blueprint generated, dispatched
    GROWING     = "growing"       # 🌳 Files being modified
    BLOOMED     = "bloomed"       # 🌸 Completed successfully
    WILTED      = "wilted"        # 🍂 Failed or abandoned
    PAUSED      = "paused"        # ⏸️  Temporarily paused

    @property
    def emoji(self) -> str:
        return {
            "planted": "🌱",
            "germinating": "🌿",
            "growing": "🌳",
            "bloomed": "🌸",
            "wilted": "🍂",
            "paused": "⏸️",
        }.get(self.value, "❓")

    @property
    def growth_percentage(self) -> int:
        """Base growth percentage for each stage."""
        return {
            "planted": 0,
            "germinating": 25,
            "growing": 50,
            "bloomed": 100,
            "wilted": 0,
            "paused": -1,  # Retains last growth value
        }.get(self.value, 0)


class Seed:
    """
    Represents a single seed in the queue.
    
    A seed is born when a user plants an idea. It grows through
    stages as SRT-1 generates blueprints and the code assistant 
    builds the result. The user can check its growth at any time.
    """

    def __init__(self, seed_id: str, intent: str, source: str = "api",
                 priority: int = 5, tags: Optional[List[str]] = None):
        self.seed_id = seed_id
        self.intent = intent              # The original idea
        self.source = source              # Where it came from: "mobile", "api", "cli", "dashboard"
        self.priority = priority           # 1 (low) to 10 (critical)
        self.tags = tags or []

        # Lifecycle
        self.stage = SeedStage.PLANTED
        self.growth = 0                    # 0-100% progress indicator
        self.created_at = datetime.now().isoformat()
        self.updated_at = datetime.now().isoformat()
        self.completed_at: Optional[str] = None

        # Blueprint (generated by SRT-1)
        self.blueprint: Optional[str] = None
        self.blueprint_path: Optional[str] = None
        self.relevant_symbols: int = 0
        self.relevant_files: int = 0

        # Execution tracking
        self.files_modified: List[str] = []
        self.operations_logged: int = 0
        self.coherence_snapshots: List[Dict] = []

        # State history (every transition logged)
        self.history: List[Dict] = [{
            "stage": SeedStage.PLANTED.value,
            "timestamp": self.created_at,
            "note": f"Seed planted from {source}",
        }]

        # Result
        self.result_summary: Optional[str] = None
        self.success: Optional[bool] = None

    def advance(self, new_stage: SeedStage, note: str = "") -> None:
        """Advance the seed to a new lifecycle stage."""
        old_stage = self.stage
        self.stage = new_stage
        self.updated_at = datetime.now().isoformat()

        # Update growth
        if new_stage.growth_percentage >= 0:
            self.growth = new_stage.growth_percentage
        # PAUSED retains current growth

        # Record history
        self.history.append({
            "stage": new_stage.value,
            "from_stage": old_stage.value,
            "timestamp": self.updated_at,
            "note": note or f"Transitioned from {old_stage.value} to {new_stage.value}",
        })

        if new_stage in (SeedStage.BLOOMED, SeedStage.WILTED):
            self.completed_at = self.updated_at
            self.success = (new_stage == SeedStage.BLOOMED)

        logger.info(f"Seed {self.seed_id}: {old_stage.emoji} {old_stage.value} → "
                     f"{new_stage.emoji} {new_stage.value}")

    def update_growth(self, percentage: int, note: str = "") -> None:
        """
        Manually update growth percentage (for fine-grained progress).
        Growth within GROWING stage can be 50-99%.
        """
        self.growth = max(0, min(100, percentage))
        self.updated_at = datetime.now().isoformat()
        if note:
            self.history.append({
                "stage": self.stage.value,
                "timestamp": self.updated_at,
                "note": f"Growth updated to {self.growth}%: {note}",
            })

    def record_coherence(self, score: float, status: str) -> None:
        """Snapshot the coherence at this point in time."""
        self.coherence_snapshots.append({
            "score": score,
            "status": status,
            "timestamp": datetime.now().isoformat(),
            "growth": self.growth,
        })

    def record_file_change(self, filepath: str) -> None:
        """Record that a file was modified as part of this seed."""
        if filepath not in self.files_modified:
            self.files_modified.append(filepath)
        # Increment growth slightly for each file modified during GROWING
        if self.stage == SeedStage.GROWING:
            scale = min(95, 50 + len(self.files_modified) * 5)
            self.growth = scale

    def to_dict(self) -> Dict[str, Any]:
        """Serialize the seed for JSON storage and API responses."""
        return {
            "seed_id": self.seed_id,
            "intent": self.intent,
            "source": self.source,
            "priority": self.priority,
            "tags": self.tags,
            "stage": self.stage.value,
            "stage_emoji": self.stage.emoji,
            "growth": self.growth,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "completed_at": self.completed_at,
            "blueprint_generated": self.blueprint is not None,
            "blueprint_path": self.blueprint_path,
            "relevant_symbols": self.relevant_symbols,
            "relevant_files": self.relevant_files,
            "files_modified": self.files_modified,
            "operations_logged": self.operations_logged,
            "coherence_snapshots": self.coherence_snapshots[-5:],  # Last 5 only
            "history": self.history,
            "result_summary": self.result_summary,
            "success": self.success,
        }

    def to_summary(self) -> Dict[str, Any]:
        """Compact summary for list views (mobile-friendly)."""
        last_coherence = None
        if self.coherence_snapshots:
            lc = self.coherence_snapshots[-1]
            last_coherence = {"score": lc["score"], "status": lc["status"]}

        return {
            "seed_id": self.seed_id,
            "intent": self.intent[:100],
            "stage": self.stage.value,
            "stage_emoji": self.stage.emoji,
            "growth": self.growth,
            "source": self.source,
            "priority": self.priority,
            "files_modified": len(self.files_modified),
            "created_at": self.created_at,
            "completed_at": self.completed_at,
            "coherence": last_coherence,
            "success": self.success,
        }

    @classmethod
    def from_dict(cls, data: Dict) -> "Seed":
        """Deserialize a seed from JSON."""
        seed = cls(
            seed_id=data["seed_id"],
            intent=data["intent"],
            source=data.get("source", "api"),
            priority=data.get("priority", 5),
            tags=data.get("tags", []),
        )
        seed.stage = SeedStage(data.get("stage", "planted"))
        seed.growth = data.get("growth", 0)
        seed.created_at = data.get("created_at", seed.created_at)
        seed.updated_at = data.get("updated_at", seed.updated_at)
        seed.completed_at = data.get("completed_at")
        seed.blueprint = data.get("blueprint")
        seed.blueprint_path = data.get("blueprint_path")
        seed.relevant_symbols = data.get("relevant_symbols", 0)
        seed.relevant_files = data.get("relevant_files", 0)
        seed.files_modified = data.get("files_modified", [])
        seed.operations_logged = data.get("operations_logged", 0)
        seed.coherence_snapshots = data.get("coherence_snapshots", [])
        seed.history = data.get("history", [])
        seed.result_summary = data.get("result_summary")
        seed.success = data.get("success")
        return seed


class SCIASeedQueue:
    """
    The seed queue: manages the full lifecycle of all seeds.
    
    This is what powers the mobile experience. A user plants a seed
    from their phone and checks back later to see it bloomed.
    
    API Endpoints (integrated into SRT-1 HTTP server):
        POST /seeds         — Plant a new seed
        GET  /seeds         — List all seeds (with filters)
        GET  /seeds/<id>    — Get detailed seed status
        PATCH /seeds/<id>   — Update seed stage/growth
        GET  /seeds/active  — Get currently active (non-completed) seeds
        GET  /seeds/stats   — Seed farm statistics
    """

    def __init__(self, queue_dir: Optional[str] = None):
        """
        Args:
            queue_dir: Where to persist the seed queue (default: .srt1/seeds/)
        """
        self.queue_dir = queue_dir or os.path.join(os.getcwd(), ".srt1", "seeds")
        os.makedirs(self.queue_dir, exist_ok=True)

        self.queue_file = os.path.join(self.queue_dir, "seed_queue.json")
        self._seeds: Dict[str, Seed] = {}
        self._seed_counter = 0

        # Load existing queue
        self._load()

    # -----------------------------------------------------------------
    # PLANTING
    # -----------------------------------------------------------------

    def plant(self, intent: str, source: str = "api",
              priority: int = 5, tags: Optional[List[str]] = None) -> Seed:
        """
        Plant a new seed. Returns the Seed object.
        
        Args:
            intent: What the user wants to build/do
            source: Where this came from ("mobile", "api", "cli", "dashboard")
            priority: 1-10 priority level
            tags: Optional tags for categorization
        """
        self._seed_counter += 1
        seed_id = f"seed_{self._seed_counter:04d}_{hashlib.md5(intent.encode()).hexdigest()[:8]}"

        seed = Seed(
            seed_id=seed_id,
            intent=intent,
            source=source,
            priority=priority,
            tags=tags,
        )

        self._seeds[seed_id] = seed
        self._save()

        logger.info(f"🌱 Seed planted: '{intent[:50]}...' (ID: {seed_id}, source: {source})")
        return seed

    # -----------------------------------------------------------------
    # LIFECYCLE TRANSITIONS
    # -----------------------------------------------------------------

    def germinate(self, seed_id: str, blueprint: str = None,
                  blueprint_path: str = None,
                  relevant_symbols: int = 0,
                  relevant_files: int = 0) -> Optional[Seed]:
        """Mark seed as germinating (blueprint generated, dispatched)."""
        seed = self._seeds.get(seed_id)
        if not seed:
            return None

        seed.advance(SeedStage.GERMINATING, "Blueprint generated and dispatched to assistant")
        seed.blueprint = blueprint
        seed.blueprint_path = blueprint_path
        seed.relevant_symbols = relevant_symbols
        seed.relevant_files = relevant_files
        self._save()
        return seed

    def start_growing(self, seed_id: str, note: str = "") -> Optional[Seed]:
        """Mark seed as growing (assistant is building)."""
        seed = self._seeds.get(seed_id)
        if not seed:
            return None
        seed.advance(SeedStage.GROWING, note or "Code assistant is building")
        self._save()
        return seed

    def bloom(self, seed_id: str, summary: str = "") -> Optional[Seed]:
        """Mark seed as bloomed (completed successfully)."""
        seed = self._seeds.get(seed_id)
        if not seed:
            return None
        seed.advance(SeedStage.BLOOMED, summary or "Seed completed successfully")
        seed.result_summary = summary
        seed.growth = 100
        self._save()
        return seed

    def wilt(self, seed_id: str, reason: str = "") -> Optional[Seed]:
        """Mark seed as wilted (failed or abandoned)."""
        seed = self._seeds.get(seed_id)
        if not seed:
            return None
        seed.advance(SeedStage.WILTED, reason or "Seed failed or was abandoned")
        seed.result_summary = reason
        self._save()
        return seed

    def pause(self, seed_id: str, reason: str = "") -> Optional[Seed]:
        """Pause a seed temporarily."""
        seed = self._seeds.get(seed_id)
        if not seed:
            return None
        seed.advance(SeedStage.PAUSED, reason or "Paused by user")
        self._save()
        return seed

    def resume(self, seed_id: str) -> Optional[Seed]:
        """Resume a paused seed (returns to GROWING)."""
        seed = self._seeds.get(seed_id)
        if not seed or seed.stage != SeedStage.PAUSED:
            return None
        seed.advance(SeedStage.GROWING, "Resumed by user")
        self._save()
        return seed

    # -----------------------------------------------------------------
    # TRACKING
    # -----------------------------------------------------------------

    def record_file_change(self, seed_id: str, filepath: str) -> None:
        """Record a file change for a growing seed."""
        seed = self._seeds.get(seed_id)
        if seed:
            seed.record_file_change(filepath)
            # Auto-advance to GROWING if still GERMINATING
            if seed.stage == SeedStage.GERMINATING:
                seed.advance(SeedStage.GROWING, f"First file modified: {filepath}")
            self._save()

    def record_coherence(self, seed_id: str, score: float, status: str) -> None:
        """Record a coherence snapshot for a seed."""
        seed = self._seeds.get(seed_id)
        if seed:
            seed.record_coherence(score, status)

    def update_growth(self, seed_id: str, percentage: int, note: str = "") -> Optional[Seed]:
        """Update growth percentage for fine-grained progress."""
        seed = self._seeds.get(seed_id)
        if seed:
            seed.update_growth(percentage, note)
            self._save()
            return seed
        return None

    # -----------------------------------------------------------------
    # QUERIES
    # -----------------------------------------------------------------

    def get_seed(self, seed_id: str) -> Optional[Dict]:
        """Get full seed details."""
        seed = self._seeds.get(seed_id)
        return seed.to_dict() if seed else None

    def list_seeds(self, stage: Optional[str] = None,
                   source: Optional[str] = None,
                   limit: int = 50) -> List[Dict]:
        """
        List seeds with optional filtering.
        Returns compact summaries sorted by most recent first.
        """
        seeds = list(self._seeds.values())

        if stage:
            seeds = [s for s in seeds if s.stage.value == stage]
        if source:
            seeds = [s for s in seeds if s.source == source]

        # Sort: active seeds first (by priority), then completed (by date)
        def sort_key(s):
            is_active = s.stage not in (SeedStage.BLOOMED, SeedStage.WILTED)
            return (not is_active, -s.priority, s.created_at)

        seeds.sort(key=sort_key)
        return [s.to_summary() for s in seeds[:limit]]

    def get_active_seeds(self) -> List[Dict]:
        """Get all seeds that are not completed (bloomed/wilted)."""
        return self.list_seeds(stage=None)  # Sorted with active first

    def get_active_seed(self) -> Optional[Dict]:
        """Get the single currently-active seed (highest priority growing/germinating)."""
        active = [s for s in self._seeds.values() 
                  if s.stage in (SeedStage.PLANTED, SeedStage.GERMINATING, SeedStage.GROWING)]
        if not active:
            return None
        active.sort(key=lambda s: (-s.priority, s.created_at))
        return active[0].to_dict()

    def get_pending_seeds(self) -> List[Dict]:
        """Get seeds that have been planted but not yet dispatched."""
        planted = [s for s in self._seeds.values() if s.stage == SeedStage.PLANTED]
        planted.sort(key=lambda s: (-s.priority, s.created_at))
        return [s.to_dict() for s in planted]

    # -----------------------------------------------------------------
    # STATISTICS (The Farm Dashboard)
    # -----------------------------------------------------------------

    def get_stats(self) -> Dict[str, Any]:
        """
        Seed farm statistics — the big picture.
        Perfect for the mobile dashboard overview.
        """
        total = len(self._seeds)
        by_stage: Dict[str, int] = {}
        by_source: Dict[str, int] = {}
        total_growth = 0
        bloomed_count = 0
        wilted_count = 0
        avg_bloom_time_seconds = 0
        bloom_times: List[float] = []

        for seed in self._seeds.values():
            # By stage
            stage_key = f"{seed.stage.emoji} {seed.stage.value}"
            by_stage[stage_key] = by_stage.get(stage_key, 0) + 1

            # By source
            by_source[seed.source] = by_source.get(seed.source, 0) + 1

            # Growth
            total_growth += seed.growth

            # Completion stats
            if seed.stage == SeedStage.BLOOMED:
                bloomed_count += 1
                if seed.completed_at and seed.created_at:
                    try:
                        created = datetime.fromisoformat(seed.created_at)
                        completed = datetime.fromisoformat(seed.completed_at)
                        bloom_times.append((completed - created).total_seconds())
                    except ValueError:
                        pass
            elif seed.stage == SeedStage.WILTED:
                wilted_count += 1

        # Success rate
        completed = bloomed_count + wilted_count
        success_rate = (bloomed_count / completed * 100) if completed > 0 else 0

        # Average bloom time
        if bloom_times:
            avg_seconds = sum(bloom_times) / len(bloom_times)
            if avg_seconds < 60:
                avg_bloom_time = f"{avg_seconds:.0f}s"
            elif avg_seconds < 3600:
                avg_bloom_time = f"{avg_seconds/60:.1f}m"
            else:
                avg_bloom_time = f"{avg_seconds/3600:.1f}h"
        else:
            avg_bloom_time = "N/A"

        return {
            "total_seeds": total,
            "by_stage": by_stage,
            "by_source": by_source,
            "average_growth": round(total_growth / total, 1) if total > 0 else 0,
            "success_rate": round(success_rate, 1),
            "bloomed": bloomed_count,
            "wilted": wilted_count,
            "active": total - bloomed_count - wilted_count,
            "avg_bloom_time": avg_bloom_time,
            "oldest_active_seed": self._oldest_active(),
        }

    def _oldest_active(self) -> Optional[Dict]:
        """Find the oldest active seed (might need attention)."""
        active = [s for s in self._seeds.values()
                  if s.stage not in (SeedStage.BLOOMED, SeedStage.WILTED)]
        if not active:
            return None
        oldest = min(active, key=lambda s: s.created_at)
        return {"seed_id": oldest.seed_id, "intent": oldest.intent[:60],
                "created_at": oldest.created_at, "stage": oldest.stage.value}

    # -----------------------------------------------------------------
    # PERSISTENCE
    # -----------------------------------------------------------------

    def _load(self) -> None:
        """Load the seed queue from disk."""
        if os.path.exists(self.queue_file):
            try:
                with open(self.queue_file, "r", encoding="utf-8") as f:
                    data = json.load(f)

                self._seed_counter = data.get("_counter", 0)
                for sid, sdata in data.get("seeds", {}).items():
                    self._seeds[sid] = Seed.from_dict(sdata)

                logger.info(f"Loaded {len(self._seeds)} seeds from queue")
            except (json.JSONDecodeError, IOError) as e:
                logger.error(f"Failed to load seed queue: {e}")

    def _save(self) -> None:
        """Save the seed queue to disk."""
        try:
            data = {
                "_counter": self._seed_counter,
                "_updated_at": datetime.now().isoformat(),
                "seeds": {sid: s.to_dict() for sid, s in self._seeds.items()},
            }
            with open(self.queue_file, "w", encoding="utf-8") as f:
                json.dump(data, f, indent=2, default=str)
        except IOError as e:
            logger.error(f"Failed to save seed queue: {e}")

    # -----------------------------------------------------------------
    # CLEANUP
    # -----------------------------------------------------------------

    def prune(self, keep_completed: int = 50) -> int:
        """
        Remove old completed seeds, keeping the most recent ones.
        Returns number of seeds pruned.
        """
        completed = [(sid, s) for sid, s in self._seeds.items()
                     if s.stage in (SeedStage.BLOOMED, SeedStage.WILTED)]
        completed.sort(key=lambda x: x[1].completed_at or "", reverse=True)

        pruned = 0
        for sid, _ in completed[keep_completed:]:
            del self._seeds[sid]
            pruned += 1

        if pruned:
            self._save()
            logger.info(f"Pruned {pruned} old completed seeds")

        return pruned


# =============================================================================
# CLI
# =============================================================================

def main():
    """Quick CLI for testing the seed queue."""
    import argparse

    parser = argparse.ArgumentParser(description="SRT-1 Seed Queue Manager")
    sub = parser.add_subparsers(dest="command")

    # Plant
    p = sub.add_parser("plant", help="Plant a new seed")
    p.add_argument("intent", help="What to build")
    p.add_argument("--source", default="cli", help="Source (cli, mobile, api)")
    p.add_argument("--priority", type=int, default=5, help="Priority 1-10")

    # List
    sub.add_parser("list", help="List all seeds")

    # Status
    s = sub.add_parser("status", help="Get seed status")
    s.add_argument("seed_id", help="Seed ID")

    # Bloom
    b = sub.add_parser("bloom", help="Mark seed as completed")
    b.add_argument("seed_id", help="Seed ID")
    b.add_argument("--summary", default="", help="Completion summary")

    # Stats
    sub.add_parser("stats", help="Show farm statistics")

    args = parser.parse_args()
    if not args.command:
        parser.print_help()
        return

    queue = SCIASeedQueue()

    if args.command == "plant":
        seed = queue.plant(args.intent, source=args.source, priority=args.priority)
        print(f"\n  {seed.stage.emoji} Seed planted: {seed.seed_id}")
        print(f"  Intent: {seed.intent}")
        print(f"  Growth: {seed.growth}%\n")

    elif args.command == "list":
        seeds = queue.list_seeds()
        if not seeds:
            print("  No seeds in the queue.")
            return
        print(f"\n  {'─' * 80}")
        for s in seeds:
            emoji = s["stage_emoji"]
            growth = f"{s['growth']}%"
            files = s["files_modified"]
            print(f"  {emoji} {s['seed_id']}  [{s['stage']}]  {growth:>4}  "
                  f"files={files}  {s['intent'][:50]}")
        print(f"  {'─' * 80}\n")

    elif args.command == "status":
        seed = queue.get_seed(args.seed_id)
        if not seed:
            print(f"  Seed {args.seed_id} not found.")
            return
        print(json.dumps(seed, indent=2))

    elif args.command == "bloom":
        seed = queue.bloom(args.seed_id, summary=args.summary)
        if seed:
            print(f"  🌸 Seed {args.seed_id} has BLOOMED!")
        else:
            print(f"  ❌ Seed not found.")

    elif args.command == "stats":
        stats = queue.get_stats()
        print(json.dumps(stats, indent=2))


if __name__ == "__main__":
    main()
